fix bf using wc

diff --git a/bin/bf b/bin/bf
--- a/bin/bf
+++ b/bin/bf
@@ -2,6 +2,48 @@
 #https://esolangs.org/wiki/Extended_Brainfuck
 extension=0 #set which extended type to use
 file=0
+lenght() {
+	#!/usr/bin/env bash
+	#
+	# wc in pure bash.
+	
+	while getopts "lcw" opt; do
+	    case $opt in
+	        l) lines=1 ;;
+	        c) bytes=1 ;;
+	        w) words=1 ;;
+	
+	        ?)
+	            printf '%s\n' "error: -$OPTARG not a valid option." >&2
+	            exit 1
+	        ;;
+	    esac
+	done
+	
+	[[ -t 0 && -f ${*: -1} ]] &&
+	    file=${*: -1}
+	
+	[[ -t 0 && ! -f $file ]] && {
+	    printf '%s\n' "wc: ${file:-null}: No such file or directory." >&2
+	    exit 1
+	}
+	
+	mapfile file_data < "${file:-/dev/stdin}"
+	
+	for line in "${file_data[@]}"; do
+	    read -ra line_split <<< "$line"
+	    ((splits+=${#line_split[@]}, chars+=${#line}))
+	done
+	
+	[[ -z $lines && -z $bytes && -z $words ]] &&
+	    ((lines=1, bytes=1, words=1))
+	
+	[[ $lines ]] && printf '%s ' "${#file_data[@]}"
+	[[ $words ]] && printf '%s ' "$splits"
+	[[ $bytes ]] && printf '%s ' "$chars"
+	
+	printf '%s\n' "$file"
+}
 if [ "$1" = -x ]; then
 	extension=1
 	shift
@@ -36,7 +78,7 @@ p=0
 if [ $file = 1 ]; then
 	for (( i=0; i<${#programf}; i++ )); do
 		a[$i]=$(printf "%d\n" \'"${programf:$i:1}")
-		p=$(( $(printf "%d\n" \'"${programf:$i:1}" | wc -c) + 1 ))
+		p=$(( $(printf "%d\n" \'"${programf:$i:1}" | lenght -c) + 1 ))
 	done
 fi
 
